### ISSUE TITLE
What is chatkit?

### ISSUE THREAD

**Issue by yzydeveloper** [egoist/chatkit-docs#1]
Doesn't chatkit have an account system? When you visit [chatkit](https://chatkit.app) you see a conversation with Rspack

![image](https://user-images.githubusercontent.com/50061726/234207478-8c856fe7-1031-4755-94fc-efecbbd1d9ab.png)

**Comment by egoist** [comment]
that’s your local history

杨兆雨 ***@***.***>于2023年4月25日 周二15:39写道：

**Comment by yzydeveloper** [comment]
Well, I found out I was accessing it through [ChatKit Share](https://chatkit.app/s/xsmWIMDFqDzazar9XPycC), leaving a history locally, how interesting! 😂

**Comment by egoist** [comment]
it only creates a chat when you click "Continue this conversation on
ChatKit"

杨兆雨 ***@***.***>于2023年4月25日 周二15:53写道：
