### ISSUE TITLE
Allow the user to pick what to Sync 

### ISSUE THREAD

**Issue by younes-io** [egoist/chatkit-docs#7]
I'm not yet a user, but maybe will be soon..

I was looking into the [Sync section](https://docs.chatkit.app/cloud-sync.html#what-s-synced) of the ChatKit docs, and was wondering maybe it could be interesting to let the user customize/pick what they might want to sync:

- App settings (including your OpenAI API key (if any) etc.)
- Chat history
- Chat settings

Maybe, I only want to sync Chat Settings, not history, and not API keys...

**Comment by egoist** [comment]
yeah, this definitely makes sense
